# Generated by Django 5.1 on 2026-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_invoice_items_invoice_items_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierreconciliation',
            name='supplier_reconciliation_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
