# Generated by Django 5.1 on 2026-09-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplierpayment_supplier_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariant'),
        ),
    ]
